#:schema node_modules/wrangler/config-schema.json
name = "sub2026"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "11f58b125f124b5ca6dd29ccc1ce9ec9" }
]

[assets]
directory = "./public"
